package com.sjsu.payments;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Card")
public class Card {
	
	@DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName = "cardId")
	private String cardId;
	  
	  @DynamoDBAttribute(attributeName = "cardPIN")  
	private String cardPIN;
	  
	  @DynamoDBAttribute(attributeName = "balance")    
	private String balance;
	
	@DynamoDBAttribute(attributeName = "userId")
	private String userId;

	
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	public void setCardId(String id) {
		cardId = id;
	}
	
	public void setCardPIN(String pin) {
		cardPIN = pin;
	}
	

	
	public String getCardId() {
		return cardId;
	}
	
	public String getCardPIN() {
		return cardPIN;
	}
	
	public String getBalance() {
		return balance;
	}

}