package com.piecoffeeshop.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Menu")

public class Menu {	
	
	private String Id;
	
	
	private String ProdId;
	
	
	private String ProdName;
	
	
	private String Cost;
	
	public void setId(String id) {
		Id = id; 
	}
	@DynamoDBHashKey(attributeName = "Id")
	public String getId() {
		return Id;
	}
	
	
	public void setProdId(String prodId) {
		ProdId = prodId;
	}
	
	public void setProdName(String prodName) {
		ProdName = prodName;
	}

	public void setCost(String cost) {
		Cost = cost;
	}
	@DynamoDBAttribute(attributeName = "Cost")
    public String getCost() {
		return Cost;
	}
    @DynamoDBAttribute(attributeName = "ProdName")
    public String getProdName() {
		return ProdName;
	}
    
    @DynamoDBAttribute(attributeName = "ProdId")
    public String getProdId() {
		return ProdId;
	}
}
